import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="theme-dark" suppressHydrationWarning>
      <head>
        <script
          // Apply theme before the app renders to prevent flicker.
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var t=localStorage.getItem('weafrica_theme');if(!t){t='dark';localStorage.setItem('weafrica_theme',t);}document.documentElement.classList.remove('theme-dark','theme-light');document.documentElement.classList.add(t==='light'?'theme-light':'theme-dark');}catch(e){}})();",
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
